workspace:
  base: /go
  path: src/github.com/gomods/athens

pipeline:
  ping:
    image: mongo:3.0
    commands:
      - sleep 15
  build:
    image: golang:1.11
    commands:
      - go test -mod=vendor ./...

services:
  mongo:
    image: mongo:3.0
    command: [ --smallfiles ]
